version: '2'
services:
    msg:
        build: .
        command: python3 app.py
        ports:
            - 5000:5000
    rcon:
        image: redis
        command: redis-server --requirepass AxD3R4T5L% --appendonly yes
        volumes:
            - redis_data:/data

volumes:
    redis_data:
